== Klassenbeschreibung
=== Topic `+Stammdaten+`
Bei diesem Modell wird noch keine Überführung der Aufzählwerte in Stammdaten vorgenommen. Der Grund ist, dass die Datenerfassung zum Zeitpunkt der Modelldokumentation bereits abgeschlossen ist und die nächste Überarbeitung voraussichtlich ab dem Jahr 2035 stattfinden wird.

=== Topic `+Fachdaten+`
Das Topic `+Fachdaten+` umfasst die fachlichen Klassen des Themas.

Im kantonalen Modell verzichtet man auf die Klassen `+SeeKanton+` und `+UferlinieGeometrie+` des Bundesmodells. Zudem sind die Abschnitte linear referenziert. Die Attribute der linearen Referenzierung sind zu den entsprechenden Klassen hinzugefügt. Die für die lineare Referenzierung erforderliche Referenzgeometrie der Uferlinie entnehme man dem Datensatz A154 "Referenzgeometrie Standgewässer".

==== Klasse `+OekomorphologieSeeufer+`
Die Klasse `+OekomorphologieSeeufer+` führt die Informationen zur Ökomorphologie des Seeufers. Die Klasse wird durch `+Methode_BAFU+` und `+Methode_IGKB+` spezialisiert. Der Einfachheit halber wird in dieser Klasse ein eigener Raumbezug hergestellt, auch wenn die Seeuferabschnitte mit anderen der Klassen `+Resultat_Plan_B_E_F+` oder `+Resultat_Plan_C_D+` übereinstimmen würden.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Kennung
| Objektidentifikator +
Aufbau: <Jahr>-<Monat>-<Tag>_<Laufnummer>
| 2009-07-01_100023
| öffentlich
m| Achsgeometrie
| Wert der Referenzgeometrie, auf welche sich der Abschnitt bezieht (vgl. Bedingungen unten)
| 1013
| öffentlich
m| LinearpositionVon
| Wert, ab dem der Abschnitt beginnt.
| 13646.9
| öffentlich
m| LinearpositionBis
| Wert, bei dem der Abschnitt endet.
| 13758.4
| öffentlich
m| Methode
| vorgegebene Werte, welche die Methode benennen, anhand derer die Daten erhoben wurden
| BAFU
| öffentlich
m| Bezeichnung_andere_Methode
| falls Methode = ‘andere’, kann diese hier genauer beschreiben werden
| CIPEL
| öffentlich
m| Aufnahmezeitpunkt
| Aufnahmezeitpunkt der Bildgrundlage, der Begehung oder Plänen, die der Erfassung zu Grunde liegt. Bei mehreren Beurteilungsgrundlagen mit unterschiedlichen Erstellungsdaten, ist das aktuellste Datum anzugeben vgl. (Niederberger et al., 2016)
| 2019-07-31
| öffentlich
m| Gesamtbeurteilung
| vorgegebene Werte als zusammenfassende Beurteilung aus den Methodeneinzelwerten
| naturfremd
| öffentlich
m| Bildpfad
| Verzeichnispfad, welcher auf das dem Abschnit zugeordneten Bild verweist
| I:\\<Pfad zur Datei>
| +++<span style="color:red;">intern</span>+++
m| Bemerkung
| Bemerkung zum Objekt
| Das ist eine Bemerkung
| +++<span style="color:red;">intern</span>+++
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
m|Kennung
3+a| * Die Werte müssen innerhalb der Klasse eindeutig sein.
* Nach der Vergabe muss der Wert unverändert bleiben.
m|Achsgeometrie
3+| Der Wert muss mit dem Wert in `+Ufergeometrie.Kennung+` des Datenmodells https://models.geo.sz.ch/AFG/SZ_Referenzgeometrie_Standgewaesser_V1.ili[SZ_Referenzgeometrie_Standgewaesser_V1] übereinstimmen.
|===

==== Klasse `+Methode_BAFU+`
Die Klasse `+Methode_BAFU+` ist eine Spezialisierung der Klasse `+OekomorphologieSeeufer+` und führt die spezifischen Informationen, welche mit der Methode BAFU erhoben werden. Mit der Methode BAFU erfolgt die Revitalisierungsbeurteilung (RB) anhand verschiedener Index-Werte (Uferstreifen, Flachwasserzone, usw.).

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Oekomorphologie_gesamt
| Beurteilung der Ökomorphologie gesamthaft
| 0.9
| öffentlich
m| Oekomorphologie_Flachwasserzone
| Beurteilung der Ökomorphologie der Flachwasserzone
| 0.8
| öffentlich
m| Oekomorphologie_Uferstreifen
| Beurteilung der Ökomorphologie des Uferstreifens
| 0.7
| öffentlich
m| Oekomorphologie_Uferlinie
| Beurteilung der Ökomorphologie der Uferlinie
| 0.9
| öffentlich
m| Oekomorphologie_Hinterland
| Beurteilung der Ökomorphologie des Hinterlandes
| 0.5
| öffentlich
m| Nutzung_Uferstreifen
| Klassierung der Nutzung des Uferstreifens
| 0.8
| öffentlich
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

==== Klasse `+Methode_IGKB+`
Die Klasse `+Methode_IGKB+` ist eine Spezialisierung der Klasse `+OekomorphologieSeeufer+` und führt die spezifischen Informationen, welche mit der Methode IGKB erhoben werden.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Gesamtbeurteilung_gewichtet
| gewichtete Gesamtbeurteilung des Uferzustandes
| 4.96
| öffentlich
m| Uferlinie
| Indexwert für die naturnahe Uferlinie in Abweichung vom Referenzzustand
| 4
| öffentlich
m| Deltabildung
| Indexwert für die Deltabildung
| 3
| öffentlich
m| Ufersubstrat
| Indexwert für das Ufersubstrat
| 5
| öffentlich
m| Litoralsubstrat
| Indexwert für das Litoralsubstrat
| -1
| öffentlich
m| Totholz
| Indexwert für das Totholz
| 1
| öffentlich
m| Hindernisse
| Indexwert für die Hindernisse
| 4
| öffentlich
m| Uferverbauung
| Indexwert für die Uferverbauung
| 3
| öffentlich
m| Durchgaengigkeit
| Indexwert für die biologische Durchgängigkeit
| -1
| öffentlich
m| Ufervegetation_landseitig
| Indexwert für die landseitige Ufervegetation bzw. -gehölz
| 3
| öffentlich
m| Roehricht
| Indexwert für den Röhricht
| -1
| öffentlich
m| Makrophyten
| Indexwert für die Makrophyten
| -1
| öffentlich
m| Veralgung
| Indexwert für die Veralgung
| 5
| öffentlich
m| Stoerfrequenz
| Indexwert für die Störfrequenz
| 3
| öffentlich
m| Kinderstube
| Indexwert für die Kinderstube
| 4
| öffentlich
m| Anbindung_Hinterland
| Indexwert für die Anbindung des Hinterlandes
| 4
| öffentlich
m| Ufertyp
| Indexwert für den Ufertyp
| 3
| öffentlich
m| Breite_Flachwasserzone
| Breite der Flachwasserzone
| 6
| öffentlich
m| Treibgut
a| Code für das Treibgut. Es gilt:

* 1: sehr gering
* 2: gering 
* 3: mässig 
* 4: stark 
* 5: sehr stark 
| 4
| öffentlich
m| Erosion
a| Code für die Erosion. Es gilt:

* 1: sehr gering
* 2: gering 
* 3: mässig 
* 4: stark 
* 5: sehr stark 
| 2
| öffentlich
m| Erholung
| Indexwert für die Erholung
| -1
| öffentlich
m| Kulturwert
a| Code für den Kulturwert. Es gilt:

* -1: nicht relevant
* 1: gering 
* 2: mässig 
* 3: gross
| 2
| öffentlich
m| Strandrasen
a| Code für den Strandrasen. Es gilt:

* -1: nicht relevant
* 1: sehr gering 
* 2: gering 
* 3: mässig 
* 4: stark 
* 5: sehr stark 
| 5
| öffentlich
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

==== Klasse `+Resultat_Plan_B_E_F+`
Die Klasse `+Resultat_Plan_B_E_F+` führt die allgemeinen Attribute zur Beschreibung

- der ökologischen und landschaftlichen Bedeutung (Klasse `+Oek_L_Bedeutung+`),
- des Nutzens für Natur und Landschaft im Verhältnis zum Aufwand (Klasse `+Nutzen_Aufwand+`) und
- der zeitlichen Priorisierung (Klasse `+Umsetzung+`).

Die Klasse ist abstrakt. Der Einfachheit halber wird in dieser Klasse ein eigener Raumbezug hergestellt, auch wenn die Seeuferabschnitte mit anderen der Klassen `+OekomorphologieSeeufer+` oder `+Resultat_Plan_C_D+` übereinstimmen würden.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Kennung
| Objektidentifikator +
Aufbau: <Jahr>-<Monat>-<Tag>_<Laufnummer>
| 2009-07-01_100023
| öffentlich
m| Achsgeometrie
| Wert der Referenzgeometrie, auf welche sich der Abschnitt bezieht (vgl. Bedingungen unten)
| 1013
| öffentlich
m| LinearpositionVon
| Wert, ab dem der Abschnitt beginnt.
| 13646.9
| öffentlich
m| LinearpositionBis
| Wert, bei dem der Abschnitt endet.
| 13758.4
| öffentlich
m| Bemerkung
| Bemerkung zum Objekt
| Das ist eine Bemerkung
| +++<span style="color:red;">intern</span>+++
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
m|Kennung
3+a| * Die Werte müssen innerhalb der Klasse eindeutig sein.
* Nach der Vergabe muss der Wert unverändert bleiben.
m|Achsgeometrie
3+| Der Wert muss mit dem Wert in `+Ufergeometrie.Kennung+` des Datenmodells https://models.geo.sz.ch/AFG/SZ_Referenzgeometrie_Standgewaesser_V1.ili[SZ_Referenzgeometrie_Standgewaesser_V1] übereinstimmen.
|===

==== Klasse `+Oek_L_Bedeutung+`
Die Klasse `+Oek_L_Bedeutung+` führt die Information über die ökologische und landschaftliche Bedeutung. Sie ist eine Spezialisierung der Klasse `+Resultat_Plan_B_E_F+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Oek_LS_Bedeutung
| Faktor der ökologischen und landschaftlichen Bedeutung
| 1.1
| öffentlich
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

==== Klasse `+Nutzen_Aufwand+`
Die Klasse `+Nutzen_Aufwand+` führt die Information über den Nutzen für Natur und Landschaft. Sie ist eine Spezialisierung der Klasse `+Resultat_Plan_B_E_F+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Nutzen_NL_Aufwand
| klassifizierter Nutzen für Natur und Landschaft im Verhältnis zum Aufwand
| 3
| öffentlich
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

==== Klasse `+Umsetzung+`
Die Klasse `+Umsetzung+` führt die Umsetzungsfristen. Sie ist eine Spezialisierung der Klasse `+Resultat_Plan_B_E_F+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Zeitfenster_geplante_Umsetzung
| codierter Wert der Umsetzungsfrist
| 12
| öffentlich
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

==== Klasse `+Resultat_Plan_C_D+`
Die Klasse `+Resultat_Plan_C_D+` führt die allgemeinen Attribute zur Beschreibung

- des berechneten Aufwertungspotentials (Klasse `+Aufwertungspotential+`; entspricht Ablaufschritt "C" der Abbildung 2 in [todo]) und
- des über GIS-Analysen berechneten Nutzens (Klasse `+Nutzen+`; entspricht Ablaufschritt "D" der Abbildung 2 in [todo]).

Die Klasse ist abstrakt und erweitert mit ihren beiden spezialisierten Klassen das Bundesmodell mit kantonalen Mehranforderungen. Der Einfachheit halber wird in dieser Klasse ein eigener Raumbezug hergestellt, auch wenn die Seeuferabschnitte mit anderen der Klassen `+OekomorphologieSeeufer+` oder `+Resultat_Plan_B_E_F+` übereinstimmen würden.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Kennung
| Objektidentifikator +
Aufbau: <Jahr>-<Monat>-<Tag>_<Laufnummer>
| 2009-07-01_100023
| öffentlich
m| Achsgeometrie
| Wert der Referenzgeometrie, auf welche sich der Abschnitt bezieht (vgl. Bedingungen unten)
| 1013
| öffentlich
m| LinearpositionVon
| Wert, ab dem der Abschnitt beginnt.
| 13646.9
| öffentlich
m| LinearpositionBis
| Wert, bei dem der Abschnitt endet.
| 13758.4
| öffentlich
m| Bemerkung
| Bemerkung zum Objekt
| Das ist eine Bemerkung
| +++<span style="color:red;">intern</span>+++
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
m|Kennung
3+a| * Die Werte müssen innerhalb der Klasse eindeutig sein.
* Nach der Vergabe muss der Wert unverändert bleiben.
m|Achsgeometrie
3+| Der Wert muss mit dem Wert in `+Ufergeometrie.Kennung+` des Datenmodells https://models.geo.sz.ch/AFG/SZ_Referenzgeometrie_Standgewaesser_V1.ili[SZ_Referenzgeometrie_Standgewaesser_V1] übereinstimmen.
|===

==== Klasse `+Aufwertungspotential+`
Die Klasse `+Aufwertungspotential+` führt die berechneten Werte für das Aufwertungspotential. Sie ist eine Spezialisierung der Klasse `+Resultat_Plan_C_D+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Aufwertungspotential
a| Code für das Aufwertungspotential. Es gilt:

* 1: gering
* 2: mittel
* 3: hoch

Der in den Daten vereinzelt auftretende Wert "0" bedeutet "NULL" und bleibt unberücksichtigt.
| 3
| +++<span style="color:red;">intern</span>+++
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

==== Klasse `+Nutzen+`
Die Klasse `+Nutzen+` führt den aufgrund einer GIS-basierten Berechnung hergeleiteten Nutzen. Sie ist eine Spezialisierung der Klasse `+Resultat_Plan_C_D+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| GIS_basiert
a| Code für den GIS-basierten Nutzen. Es gilt:

* 1: kein/gering
* 2: mittel
* 3: hoch

Der in den Daten vereinzelt auftretende Wert "0" bedeutet "NULL" und bleibt unberücksichtigt.
| 2
| +++<span style="color:red;">intern</span>+++
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

ifdef::backend-pdf[]
<<<
endif::[]
