== Klassenbeschreibung
=== Topic `+Stammdaten+`
Bei diesem Modell wird noch keine Überführung der Aufzählwerte in Stammdaten vorgenommen. Der Grund ist, dass die Datenerfassung zum Zeitpunkt der Modelldokumentation bereits abgeschlossen ist und die nächste Überarbeitung voraussichtlich ab dem Jahr 2035 stattfinden wird.

=== Topic `+Fachdaten+`
Das Topic `+Fachdaten+` umfasst die fachlichen Klassen des Themas.

Im kantonalen Modell verzichtet man auf die Klassen `+SeeKanton+` und `+UferlinieGeometrie+` des Bundesmodells. Zudem sind die Abschnitte linear referenziert. Die Attribute der linearen Referenzierung sind zu den entsprechenden Klassen hinzugefügt. Die für die lineare Referenzierung erforderliche Referenzgeometrie der Uferlinie entnehme man dem Datensatz A154 "Referenzgeometrie Standgewässer".

==== Klasse `+OekomorphologieSeeufer+`
Die Klasse `+OekomorphologieSeeufer+` führt die Informationen zur Ökomorphologie des Seeufers. Die Klasse wird durch `+Methode_BAFU+` und `+Methode_IGKB+` spezialisiert. Der Einfachheit halber wird in dieser Klasse ein eigener Raumbezug hergestellt, auch wenn die Seeuferabschnitte mit anderen Abschnitten der Klassen `+Resultat_Plan_B_E_F+` oder `+Resultat_Plan_C_D+` übereinstimmen würden.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Kennung
| Objektidentifikator +
Aufbau: <Jahr>-<Monat>-<Tag>_<Laufnummer>
| 2009-07-01_100023
| öffentlich
m| Achsgeometrie
| Wert der Referenzgeometrie, auf welche sich der Abschnitt bezieht (vgl. Bedingungen unten)
| 1013
| öffentlich
m| LinearpositionVon
| Wert, ab dem der Abschnitt beginnt.
| 13646.9
| öffentlich
m| LinearpositionBis
| Wert, bei dem der Abschnitt endet.
| 13758.4
| öffentlich
m| Methode
| vorgegebene Werte aus der Aufzählung `+Methode+`, welche die Methode benennen, anhand derer die Daten erhoben wurden
| BAFU
| öffentlich
m| Bezeichnung_andere_Methode
| falls Methode = ‘andere’, kann diese hier genauer beschreiben werden
| CIPEL
| öffentlich
m| Aufnahmezeitpunkt
| Aufnahmezeitpunkt der Bildgrundlage, der Begehung oder Plänen, die der Erfassung zu Grunde liegt. Bei mehreren Beurteilungsgrundlagen mit unterschiedlichen Erstellungsdaten, ist das aktuellste Datum anzugeben vgl. (Niederberger et al., 2016)
| 2019-07-31
| öffentlich
m| Gesamtbeurteilung
| vorgegebene Werte aus der Aufzählung `+Beurteilung+` als zusammenfassende Beurteilung aus den Methodeneinzelwerten
| naturfremd
| öffentlich
m| Bildpfad
| Verzeichnispfad, welcher auf das dem Abschnit zugeordneten Bild verweist
| I:\\<Pfad zur Datei>
| +++<span style="color:red;">intern</span>+++
m| Bemerkung
| Bemerkung zum Objekt
| Das ist eine Bemerkung
| +++<span style="color:red;">intern</span>+++
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
m|Kennung
3+a| * Die Werte müssen innerhalb der Klasse eindeutig sein.
* Nach der Vergabe muss der Wert unverändert bleiben.
m|Achsgeometrie
3+| Der Wert muss mit dem Wert in `+Ufergeometrie.Kennung+` des Datenmodells "SZ_Referenzgeometrie_Standgewaesser_V1" (A154) übereinstimmen.
|===

==== Klasse `+Methode_BAFU+`
Die Klasse `+Methode_BAFU+` ist eine Spezialisierung der Klasse `+OekomorphologieSeeufer+` und führt die spezifischen Informationen, welche mit der Methode BAFU erhoben werden. Mit der Methode BAFU erfolgt die Revitalisierungsbeurteilung (RB) anhand verschiedener Index-Werte (Uferstreifen, Flachwasserzone, usw.).

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Oekomorphologie_gesamt
a| Beurteilung der Ökomorphologie gesamthaft. Es gilt:

* 0.8 – 1 = naturnah, natürlich
* 0.6 - <0.8 = wenig beeinträchtigt
* 0.4  -<0.6 = beeinträchtigt
* 0.2 - <0.4 = naturfremd
* 0.0 - <0.2 = künstlich
| 0.8
| öffentlich
m| Oekomorphologie_Flachwasserzone
a| Beurteilung der Ökomorphologie der Flachwasserzone. Es gilt:

* 0.8 – 1 = naturnah, natürlich
* 0.6 - <0.8 = wenig beeinträchtigt
* 0.4  -<0.6 = beeinträchtigt
* 0.2 - <0.4 = naturfremd
* 0.0 - <0.2 = künstlich
| 0.8
| öffentlich
m| Oekomorphologie_Uferstreifen
a| Beurteilung der Ökomorphologie des Uferstreifens. Es gilt:

* 0.8 – 1 = naturnah, natürlich
* 0.6 - <0.8 = wenig beeinträchtigt
* 0.4  -<0.6 = beeinträchtigt
* 0.2 - <0.4 = naturfremd
* 0.0 - <0.2 = künstlich
| 0.7
| öffentlich
m| Oekomorphologie_Uferlinie
a| Beurteilung der Ökomorphologie der Uferlinie. Es gilt:

* 0.8 – 1 = naturnah, natürlich
* 0.6 - <0.8 = wenig beeinträchtigt
* 0.4  -<0.6 = beeinträchtigt
* 0.2 - <0.4 = naturfremd
* 0.0 - <0.2 = künstlich
| 0.9
| öffentlich
m| Oekomorphologie_Hinterland
a| Beurteilung der Ökomorphologie des Hinterlandes. Es gilt:

* 0.8 – 1 = naturnah, natürlich
* 0.6 - <0.8 = wenig beeinträchtigt
* 0.4  -<0.6 = beeinträchtigt
* 0.2 - <0.4 = naturfremd
* 0.0 - <0.2 = künstlich
| 0.5
| öffentlich
m| Nutzung_Uferstreifen
| Klassierung der Nutzung des Uferstreifens
| 0.8
| öffentlich
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

==== Klasse `+Methode_IGKB+`
Die Klasse `+Methode_IGKB+` ist eine Spezialisierung der Klasse `+OekomorphologieSeeufer+` und führt die spezifischen Informationen, welche mit der Methode IGKB erhoben werden.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Gesamtbeurteilung_gewichtet
| gewichtete Gesamtbeurteilung des Uferzustandes
| 4.96
| öffentlich
m| Uferlinie
a| Indexwert für die naturnahe Uferlinie in Abweichung vom Referenzzustand. Es gilt:

* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| 4
| öffentlich
m| Deltabildung
a| Indexwert für die Deltabildung. Es gilt:

* -1 = nicht relevant
* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| 3
| öffentlich
m| Ufersubstrat
a| Indexwert für das Ufersubstrat. Es gilt:

* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| 5
| öffentlich
m| Litoralsubstrat
a| Indexwert für das Litoralsubstrat. Es gilt:

* -1 = nicht relevant
* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| -1
| öffentlich
m| Totholz
a| Indexwert für das Totholz. Es gilt:

* -1 = nicht zu erwarten
* 1 = sehr gering
* 3 = mässig
* 5 = sehr stark
| 1
| öffentlich
m| Hindernisse
a| Indexwert für die Hindernisse. Es gilt:

* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| 4
| öffentlich
m| Uferverbauung
a| Indexwert für die Uferverbauung. Es gilt:

* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| 3
| öffentlich
m| Durchgaengigkeit
a| Indexwert für die biologische Durchgängigkeit. Es gilt:

* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| -1
| öffentlich
m| Ufervegetation_landseitig
a| Indexwert für die landseitige Ufervegetation bzw. -gehölz. Es gilt:

* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| 3
| öffentlich
m| Roehricht
a| Indexwert für den Röhricht. Es gilt:

* -1 = nicht zu erwarten
* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| -1
| öffentlich
m| Makrophyten
a| Indexwert für die Makrophyten. Es gilt:

* -1 = nicht zu erwarten
* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| -1
| öffentlich
m| Veralgung
a| Indexwert für die Veralgung. Es gilt:

* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| 5
| öffentlich
m| Stoerfrequenz
a| Indexwert für die Störfrequenz. Es gilt:

* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| 3
| öffentlich
m| Kinderstube
a| Indexwert für die Kinderstube. Es gilt:

* 1 = Jungfisch und Strukturen
* 3 = Jungfisch oder Strukturen
* 5 = weder Jungfisch noch Strukturen
| 4
| öffentlich
m| Anbindung_Hinterland
a| Indexwert für die Anbindung des Hinterlandes. Es gilt:

* 1 = sehr gering
* 2 = gering
* 3 = mässig
* 4 = stark
* 5 = sehr stark
| 4
| öffentlich
m| Ufertyp
a| Indexwert für den Ufertyp. Es gilt:

* 1 = Steilufer
* 2 = mittelsteiles Ufer
* 3 = Flachufer
* 4= sehr steiles Ufer
| 3
| öffentlich
m| Breite_Flachwasserzone
| Breite der Flachwasserzone
| 6
| öffentlich
m| Treibgut
a| Code für das Treibgut. Es gilt:

* 1: sehr gering
* 2: gering
* 3: mässig
* 4: stark
* 5: sehr stark
| 4
| öffentlich
m| Erosion
a| Code für die Erosion. Es gilt:

* 1: sehr gering
* 2: gering
* 3: mässig
* 4: stark
* 5: sehr stark
| 2
| öffentlich
m| Erholung
a| Indexwert für die Erholung und Freizeitnutzung. Es gilt:

* 1: sehr gut
* 3: gut
* 5: mässig
* 96: nicht relevant (= Ufer nicht zugänglich)
* 99: unbekannt
| -1
| öffentlich
m| Kulturwert
a| Code für den Kulturwert. Es gilt:

* -1: nicht relevant
* 1: gering
* 2: mässig
* 3: gross
| 2
| öffentlich
m| Strandrasen
a| Code für den Strandrasen. Es gilt:

* -1: nicht relevant
* 1: sehr gering
* 2: gering
* 3: mässig
* 4: stark
* 5: sehr stark
| 5
| öffentlich
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

==== Klasse `+Resultat_Plan_B_E_F+`
Die Klasse `+Resultat_Plan_B_E_F+` führt die allgemeinen Attribute zur Beschreibung:

- der ökologischen und landschaftlichen Bedeutung (Klasse `+Oek_L_Bedeutung+`),
- des Nutzens für Natur und Landschaft im Verhältnis zum Aufwand (Klasse `+Nutzen_Aufwand+`) und
- der zeitlichen Priorisierung (Klasse `+Umsetzung+`).

Die Klasse ist abstrakt. Der Einfachheit halber wird in dieser Klasse ein eigener Raumbezug hergestellt, auch wenn die Seeuferabschnitte mit anderen Abschnitten der Klassen `+OekomorphologieSeeufer+` oder `+Resultat_Plan_C_D+` übereinstimmen würden.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Kennung
| Objektidentifikator +
Aufbau: <Jahr>-<Monat>-<Tag>_<Laufnummer>
| 2009-07-01_100023
| öffentlich
m| Achsgeometrie
| Wert der Referenzgeometrie, auf welche sich der Abschnitt bezieht (vgl. Bedingungen unten)
| 1013
| öffentlich
m| LinearpositionVon
| Wert, ab dem der Abschnitt beginnt.
| 13646.9
| öffentlich
m| LinearpositionBis
| Wert, bei dem der Abschnitt endet.
| 13758.4
| öffentlich
m| Bemerkung
| Bemerkung zum Objekt
| Das ist eine Bemerkung
| +++<span style="color:red;">intern</span>+++
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
m|Kennung
3+a| * Die Werte müssen innerhalb der Klasse eindeutig sein.
* Nach der Vergabe muss der Wert unverändert bleiben.
m|Achsgeometrie
3+| Der Wert muss mit dem Wert in `+Ufergeometrie.Kennung+` des Datenmodells "SZ_Referenzgeometrie_Standgewaesser_V1" (A154) übereinstimmen.
|===

==== Klasse `+Oek_L_Bedeutung+`
Die Klasse `+Oek_L_Bedeutung+` führt die Information über die ökologische und landschaftliche Bedeutung. Sie ist eine Spezialisierung der Klasse `+Resultat_Plan_B_E_F+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Oek_LS_Bedeutung
| ökologische und landschaftliche Bedeutung; Faktor zwischen 0.7 und 1.3
| 1.1
| öffentlich
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

==== Klasse `+Nutzen_Aufwand+`
Die Klasse `+Nutzen_Aufwand+` führt die Information über den Nutzen für Natur und Landschaft. Sie ist eine Spezialisierung der Klasse `+Resultat_Plan_B_E_F+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Nutzen_NL_Aufwand
a| klassifizierter Nutzen für Natur und Landschaft im Verhältnis zum Aufwand. Es gilt:

* 1: gering
* 2: mittel
* 3: hoch
| 3
| öffentlich
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

==== Klasse `+Umsetzung+`
Die Klasse `+Umsetzung+` führt die Umsetzungsfristen. Sie ist eine Spezialisierung der Klasse `+Resultat_Plan_B_E_F+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Zeitfenster_geplante_Umsetzung
a| Codierter Wert der Umsetzungsfrist. Es gilt:

* 0: nicht bestimmt
* 1: bis 2024
* 2: 2025-2028
* 3: 2029-2032
* 4: 2033-2036
* 5: 2037-2040
* 6: 2041 oder später

Hinweis: Während der Datenerfassung änderte der Bund die Werte für die Umsetzungsfrist. Im Sinne der Einheitlichkeit entschied man, die Datenerfassung mit den alten Werten abzuschliessen.
| 4
| öffentlich
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

==== Klasse `+Resultat_Plan_C_D+`
Die Klasse `+Resultat_Plan_C_D+` führt die allgemeinen Attribute zur Beschreibung:

- des berechneten Aufwertungspotentials (Klasse `+Aufwertungspotential+`; entspricht Ablaufschritt "C" in Abbildung 2 von <<allgemeines.adoc#doc-07,[7]>>) und
- des über GIS-Analysen berechneten Nutzens (Klasse `+Nutzen+`; entspricht Ablaufschritt "D" in Abbildung 2 von <<allgemeines.adoc#doc-07,[7]>>).

Die Klasse ist abstrakt und erweitert mit ihren beiden spezialisierten Klassen das Bundesmodell mit kantonalen Mehranforderungen. Der Einfachheit halber wird in dieser Klasse ein eigener Raumbezug hergestellt, auch wenn die Seeuferabschnitte mit anderen Abschnitten der Klassen `+OekomorphologieSeeufer+` oder `+Resultat_Plan_B_E_F+` übereinstimmen würden.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Kennung
| Objektidentifikator +
Aufbau: <Jahr>-<Monat>-<Tag>_<Laufnummer>
| 2009-07-01_100023
| öffentlich
m| Achsgeometrie
| Wert der Referenzgeometrie, auf welche sich der Abschnitt bezieht (vgl. Bedingungen unten)
| 1013
| öffentlich
m| LinearpositionVon
| Wert, ab dem der Abschnitt beginnt.
| 13646.9
| öffentlich
m| LinearpositionBis
| Wert, bei dem der Abschnitt endet.
| 13758.4
| öffentlich
m| Bemerkung
| Bemerkung zum Objekt
| Das ist eine Bemerkung
| +++<span style="color:red;">intern</span>+++
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
m|Kennung
3+a| * Die Werte müssen innerhalb der Klasse eindeutig sein.
* Nach der Vergabe muss der Wert unverändert bleiben.
m|Achsgeometrie
3+| Der Wert muss mit dem Wert in `+Ufergeometrie.Kennung+` des Datenmodells "SZ_Referenzgeometrie_Standgewaesser_V1" (A154) übereinstimmen.
|===

==== Klasse `+Aufwertungspotential+`
Die Klasse `+Aufwertungspotential+` führt die berechneten Werte für das Aufwertungspotential. Sie ist eine Spezialisierung der Klasse `+Resultat_Plan_C_D+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Aufwertungspotential
a| Code für das Aufwertungspotential. Es gilt:

* 1: gering
* 2: mittel
* 3: hoch

Der in den Daten vereinzelt auftretende Wert "0" bedeutet "NULL" und bleibt unberücksichtigt.
| 3
| +++<span style="color:red;">intern</span>+++
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

==== Klasse `+Nutzen+`
Die Klasse `+Nutzen+` führt den aufgrund einer GIS-basierten Berechnung hergeleiteten Nutzen. Sie ist eine Spezialisierung der Klasse `+Resultat_Plan_C_D+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| GIS_basiert
a| Code für den GIS-basierten Nutzen. Es gilt:

* 1: kein/gering
* 2: mittel
* 3: hoch

Der in den Daten vereinzelt auftretende Wert "0" bedeutet "NULL" und bleibt unberücksichtigt.
| 2
| +++<span style="color:red;">intern</span>+++
4+| *Beziehungsattribute*
4+| - - -
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
4+| - - -
|===

ifdef::backend-pdf[]
<<<
endif::[]
