== Modelltransformationen
=== Transformation ins minimale Geodatenmodell des Bundes
* Quellmodell: Das hier beschriebene Datenmodell
* Zielmodell: http://models.geo.admin.ch/BAFU/Revitalisierung_Seen_V1_2.ili[Revitalisierung_Seen_V1_2 (Version: 2021-09-13)]

==== Allgemeines
Die beiden Klassen `+OekomorphologieSeeufer+` und `+Resultat_Plan_B_E_F+` weisen im Bundesmodell eine Beziehung zur Klasse `+Uferlinie_Geometrie+` auf. Damit wäre es möglich, dass sich Objekte der beiden Klassen auf die gleiche Uferliniengeometrie beziehen, was im kantonalen Modell nicht der Fall ist. Bei der Überführung der Daten ins Bundesmodell liegt es im Ermessen der zuständigen Person, ob sie gleiche Uferlinienstücke redundanzfrei abfüllt oder gleiche Abschnitte mehrfach einträgt.

Die Klasse `+Resultat_Plan_C_D+` ist nicht Teil des Bundesmodells und bleibt nachfolgend unbehandelt.

==== Klasse `+SeeKanton+`
Die Informationen zum See sind im Thema "Referenzgeometrie Standgewässer (A154)" beschrieben. Die Quellattribute stammen von diesem Modell.

Die Bezeichnung des Attributs erfolgt nach dem Muster <Modellname>.<Topicname>.<Klassenname>.<Attributname>.
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| `+SZ+` (fix)
m| Kanton
m| SZ_Referenzgeometrie_Standgewaesser_V1.Referenzgeometrie.Ufergeometrie.Kennung
m| ID_Uferlinie
| - - -
m| SeeKennung
m| SZ_Referenzgeometrie_Standgewaesser_V1.Referenzgeometrie.Ufergeometrie.Gewaessername
m| Name_See
| aus `+Ufergeometrie.Geometrie+` berechneter Wert
m| Uferlinie_Laenge_m
|===

==== Klasse `+Uferlinie_Geometrie+`
Die Informationen zum See sind im Thema "Referenzgeometrie Standgewässer (A154)" beschrieben. Die Quellattribute stammen daher von diesem Modell.
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| dynamisch segmentierte Geometrie aus `+OekomorphologieSeeufer.Achsgeometrie+` und den Angaben zu `+OekomorphologieSeeufer.LinearpositionVon+` und `+OekomorphologieSeeufer.LinearpositionBis+`
m| UferTeilstueck
m| SZ_Referenzgeometrie_Standgewaesser_V1.Referenzgeometrie.Ufergeometrie.Publikationsdatum
m| DatumUferlinie
|===

==== Klasse `+OekomorphologieSeeufer+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| `+SZ+` (fix)
m| Kanton
| `+Kanton+`
m| ID_Uferlinie
m| Methode
m| Methode
m| Bezeichnung_andere_Methode
m| Bezeichnung_andere_Methode
m| Aufnahmezeitpunkt
m| Aufnahmezeitpunkt
m| Gesamtbeurteilung
m| Gesamtbeurteilung_Oekomorphologie
|===

==== Klasse `+Methode_BAFU+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
m| Oekomorphologie_Flachwasserzone
m| RB
m| Oekomorphologie_Uferstreifen
m| RBUS
m| Oekomorphologie_Uferstreifen
m| RBFWZ
m| Oekomorphologie_Uferlinie
m| RBUL
m| Oekomorphologie_Hinterland
m| RBHL
|===

==== Klasse `+Methode_IGKB+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
m| Gesamtbeurteilung_gewichtet
m| INDEX
m| Uferlinie
m| UFERLINIE
m| Deltabildung
m| DELTA
m| Ufersubstrat
m| UFERSUB
m| Litoralsubstrat
m| LITSUB
m| Totholz
m| TOTHOLZ
m| Hindernisse
m| HINDERNIS
m| Uferverbauung
m| UFERVERBAU
m| Durchgaengigkeit
m| BIODURCH
m| Ufervegetation_landseitig
m| UFERGEH
m| Roehricht
m| ROEHRICHT
m| Makrophyten
m| MAKROPHYT
m| Veralgung
m| ALGEN
m| Stoerfrequenz
m| REFUGIUM
m| Kinderstube
m| KINDERSTUB
m| Anbindung_Hinterland
m| HINTERLAND
m| Ufertyp
m| UFERTYP
m| Breite_Flachwasserzone
m| BREITEFWZ
|===

==== Klasse `+Resultat_Plan_B_E_F+`
Die Informationen zum See sind im Thema "Referenzgeometrie Standgewässer (A154)" beschrieben. Das Quellattribut zu `+ID_Uferlinie+` stammt daher von diesem Modell.
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| `+SZ+` (fix)
m| Kanton
m| SZ_Referenzgeometrie_Standgewaesser_V1.Referenzgeometrie.Ufergeometrie.Kennung
m| ID_Uferlinie
|===

==== Klasse `+Oek_L_Bedeutung+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
m| Oek_LS_Bedeutung
m| OEB
|===

==== Klasse `+Nutzen_Aufwand+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
m| Nutzen_NL_Aufwand
m| NUTZEN
|===

==== Klasse `+Umsetzung+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
m| Zeitfenster_geplante_Umsetzung
m| FRIST
|===

ifdef::backend-pdf[]
<<<
endif::[]
